#!/usr/bin/env bash
# Claude Code adapter — installs core/ content into ~/.claude/.
#
# Skills:  core/skills/<name>/SKILL.md     -> ~/.claude/skills/<name>      (symlink)
# Rules:   core/rules/*.md                 -> ~/.claude/rules/*.md         (symlink)
#          (and a generated CLAUDE.cowork.md that @-includes them)
# Agents:  core/agents/*.md                -> ~/.claude/agents/*.md        (symlink)
# MCP:     core/mcp/servers.json           -> ~/.claude/mcp.template.json  (copy, not symlink)
#
# CLAUDE.md handling
#   We never overwrite an existing ~/.claude/CLAUDE.md authored by the user.
#   We write ~/.claude/CLAUDE.cowork.md containing @-includes for every linked
#   rule, and (only if no CLAUDE.md exists) drop a minimal CLAUDE.md that
#   @-includes the cowork file.

set -euo pipefail

adapter_claude::name()     { echo "claude"; }
adapter_claude::target()   { echo "${CLAUDE_HOME:-$HOME/.claude}"; }
adapter_claude::detect()   { [[ -d "$(adapter_claude::target)" ]]; }
adapter_claude::supports() { echo "skills rules agents mcp"; }

adapter_claude::install_skills() {
  local target; target="$(adapter_claude::target)/skills"
  local src="$COWORK_ROOT/core/skills"
  [[ -d "$src" ]] || { cowork::warn "no core/skills dir"; return 0; }

  cowork::log "claude: installing skills -> $target"
  mkdir -p "$target"
  local entry name skill_md
  for entry in "$src"/*; do
    [[ -d "$entry" ]] || continue
    name="$(basename "$entry")"
    skill_md="$entry/SKILL.md"
    if [[ -f "$skill_md" ]] && ! cowork::targets_tool "$skill_md" "claude"; then
      cowork::dim "   skipping $name (tools: excludes claude)"
      continue
    fi
    cowork::link "$entry" "$target/$name"
  done
}

adapter_claude::install_rules() {
  local target_dir; target_dir="$(adapter_claude::target)"
  local rules_dir="$target_dir/rules"
  local src="$COWORK_ROOT/core/rules"
  [[ -d "$src" ]] || { cowork::warn "no core/rules dir"; return 0; }

  cowork::log "claude: installing rules -> $rules_dir"
  mkdir -p "$rules_dir"

  local entry linked=()
  for entry in "$src"/*.md; do
    [[ -f "$entry" ]] || continue
    if ! cowork::targets_tool "$entry" "claude"; then
      cowork::dim "   skipping $(basename "$entry") (tools: excludes claude)"
      continue
    fi
    cowork::link "$entry" "$rules_dir/$(basename "$entry")"
    linked+=("rules/$(basename "$entry")")
  done

  local cowork_md="$target_dir/CLAUDE.cowork.md"
  {
    echo "# happy-cowork: persistent rules"
    echo ""
    echo "Generated by \`bin/cowork install\`. Do not edit by hand."
    echo "Source of truth: $COWORK_ROOT/core/rules/"
    echo ""
    local f
    for f in "${linked[@]}"; do
      echo "@$f"
    done
  } > "$cowork_md"
  cowork::dim "   wrote $cowork_md"

  local user_md="$target_dir/CLAUDE.md"
  if [[ ! -e "$user_md" ]]; then
    cat > "$user_md" <<'__CLAUDE_MD__'
# CLAUDE.md

Personal Claude Code instructions.

@CLAUDE.cowork.md

<!-- Add your own preferences below; CLAUDE.cowork.md is regenerated on every
     `cowork install` and should not be edited directly. -->
__CLAUDE_MD__
    cowork::dim "   wrote $user_md (initial)"
  else
    cowork::dim "   ~/.claude/CLAUDE.md exists; ensure it contains '@CLAUDE.cowork.md' to pick up rules"
  fi
}

adapter_claude::install_agents() {
  local target; target="$(adapter_claude::target)/agents"
  local src="$COWORK_ROOT/core/agents"
  [[ -d "$src" ]] || { cowork::warn "no core/agents dir"; return 0; }

  cowork::log "claude: installing agents -> $target"
  mkdir -p "$target"
  local entry
  for entry in "$src"/*.md; do
    [[ -f "$entry" ]] || continue
    if ! cowork::targets_tool "$entry" "claude"; then
      cowork::dim "   skipping $(basename "$entry") (tools: excludes claude)"
      continue
    fi
    cowork::link "$entry" "$target/$(basename "$entry")"
  done
}

adapter_claude::install_mcp() {
  local target_dir; target_dir="$(adapter_claude::target)"
  local src="$COWORK_ROOT/core/mcp/servers.json"
  [[ -f "$src" ]] || { cowork::warn "no core/mcp/servers.json"; return 0; }

  local target_file="$target_dir/mcp.template.json"
  cowork::log "claude: copying MCP template -> $target_file"
  cp "$src" "$target_file"
  cowork::dim "   merge interesting servers into your Claude MCP config (claude mcp add ...)"
}

adapter_claude::install() {
  local categories="${1:-all}"

  cowork::log "claude: target = $(adapter_claude::target)"
  if ! adapter_claude::detect; then
    cowork::warn "claude home not found at $(adapter_claude::target); creating it"
    mkdir -p "$(adapter_claude::target)"
  fi

  if [[ "$categories" == "all" || "$categories" == *skills* ]]; then
    adapter_claude::install_skills
  fi
  if [[ "$categories" == "all" || "$categories" == *rules*  ]]; then
    adapter_claude::install_rules
  fi
  if [[ "$categories" == "all" || "$categories" == *agents* ]]; then
    adapter_claude::install_agents
  fi
  if [[ "$categories" == "all" || "$categories" == *mcp*    ]]; then
    adapter_claude::install_mcp
  fi
}

adapter_claude::uninstall() {
  local target; target="$(adapter_claude::target)"
  cowork::log "claude: removing symlinks pointing at $COWORK_ROOT"
  local dir entry
  for dir in "$target/skills" "$target/rules" "$target/agents"; do
    [[ -d "$dir" ]] || continue
    for entry in "$dir"/*; do
      [[ -e "$entry" || -L "$entry" ]] || continue
      cowork::unlink_if_ours "$entry" "$COWORK_ROOT" || true
    done
  done
  if [[ -f "$target/CLAUDE.cowork.md" ]]; then
    rm "$target/CLAUDE.cowork.md"
    cowork::dim "   removed $target/CLAUDE.cowork.md"
  fi
  if [[ -f "$target/mcp.template.json" ]]; then
    rm "$target/mcp.template.json"
    cowork::dim "   removed $target/mcp.template.json"
  fi
  cowork::dim "   note: ~/.claude/CLAUDE.md left intact; remove the '@CLAUDE.cowork.md' line manually if desired"
}

adapter_claude::doctor() {
  local target; target="$(adapter_claude::target)"
  cowork::log "claude doctor: target = $target"
  if ! adapter_claude::detect; then
    cowork::warn "   target directory does not exist"
    return 1
  fi

  local ok fail entry target_path

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/skills/*/; do
    [[ -d "$entry" ]] || continue
    target_path="$target/skills/$(basename "${entry%/}")"
    if [[ -L "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   skills: $ok linked, $fail missing"

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/rules/*.md; do
    [[ -f "$entry" ]] || continue
    target_path="$target/rules/$(basename "$entry")"
    if [[ -L "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   rules:  $ok linked, $fail missing"

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/agents/*.md; do
    [[ -f "$entry" ]] || continue
    target_path="$target/agents/$(basename "$entry")"
    if [[ -L "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   agents: $ok linked, $fail missing"

  [[ -f "$target/CLAUDE.cowork.md" ]] && cowork::info "   CLAUDE.cowork.md: present" || cowork::info "   CLAUDE.cowork.md: missing"
  [[ -f "$target/mcp.template.json" ]] && cowork::info "   mcp:    template present"  || cowork::info "   mcp:    no template"
}
