#!/usr/bin/env bash
# GitHub Copilot adapter — installs core/ content into ~/.copilot/.
#
# GitHub Copilot (CLI + IDE chat) reads:
#   - Skills:       ~/.copilot/skills/<name>/SKILL.md
#   - Instructions: ~/.copilot/instructions/*.instructions.md
#   - Agents:       ~/.copilot/agents/*.md           (subagent personas)
#   - MCP:          ~/.copilot/mcp-servers.json      (hand-edited; we drop a template)
#
# Mapping
#   core/skills/<name>/SKILL.md  -> ~/.copilot/skills/<name>                       (symlink)
#   core/rules/<name>.md         -> ~/.copilot/instructions/<name>.instructions.md (rendered with applyTo: '**')
#   core/agents/<name>.md        -> ~/.copilot/agents/<name>.md                    (symlink)
#   core/mcp/servers.json        -> ~/.copilot/mcp.template.json                   (copy)
#
# Why we render rules instead of symlinking:
#   Copilot expects an `applyTo:` field in instruction frontmatter so it can scope
#   the file to globs. Our core rules have no such field, so we generate a thin
#   wrapper that adds `applyTo: '**'` and pulls in the original via a markdown
#   include link (the rule body is also inlined to keep the file self-contained).

set -euo pipefail

adapter_copilot::name()     { echo "copilot"; }
adapter_copilot::target()   { echo "${COPILOT_HOME:-$HOME/.copilot}"; }
adapter_copilot::detect()   { [[ -d "$(adapter_copilot::target)" ]]; }
adapter_copilot::supports() { echo "skills rules agents mcp"; }

adapter_copilot::install_skills() {
  local target; target="$(adapter_copilot::target)/skills"
  local src="$COWORK_ROOT/core/skills"
  [[ -d "$src" ]] || { cowork::warn "no core/skills dir"; return 0; }

  cowork::log "copilot: installing skills -> $target"
  mkdir -p "$target"
  local entry name skill_md
  for entry in "$src"/*; do
    [[ -d "$entry" ]] || continue
    name="$(basename "$entry")"
    skill_md="$entry/SKILL.md"
    if [[ -f "$skill_md" ]] && ! cowork::targets_tool "$skill_md" "copilot"; then
      cowork::dim "   skipping $name (tools: excludes copilot)"
      continue
    fi
    cowork::link "$entry" "$target/$name"
  done
}

adapter_copilot::install_rules() {
  local target; target="$(adapter_copilot::target)/instructions"
  local src="$COWORK_ROOT/core/rules"
  [[ -d "$src" ]] || { cowork::warn "no core/rules dir"; return 0; }

  cowork::log "copilot: rendering rules -> $target/*.instructions.md"
  mkdir -p "$target"
  local entry name out body
  for entry in "$src"/*.md; do
    [[ -f "$entry" ]] || continue
    if ! cowork::targets_tool "$entry" "copilot"; then
      cowork::dim "   skipping $(basename "$entry") (tools: excludes copilot)"
      continue
    fi
    name="$(basename "$entry" .md)"
    out="$target/${name}.instructions.md"

    # Strip any existing frontmatter from the source body so we can prepend ours.
    body="$(awk '
      BEGIN { in_fm = 0; started = 0 }
      /^---[[:space:]]*$/ {
        if (!started) { started = 1; in_fm = 1; next }
        else if (in_fm) { in_fm = 0; next }
      }
      !in_fm { print }
    ' "$entry")"

    {
      echo "---"
      echo "applyTo: '**'"
      echo "description: 'happy-cowork rule: ${name} (regenerated by cowork install)'"
      echo "---"
      echo ""
      echo "<!-- Generated from $entry by adapters/copilot/adapter.sh. Do not edit by hand. -->"
      echo ""
      printf '%s\n' "$body"
    } > "$out"
    cowork::dim "   rendered $out"
  done
}

adapter_copilot::install_agents() {
  local target; target="$(adapter_copilot::target)/agents"
  local src="$COWORK_ROOT/core/agents"
  [[ -d "$src" ]] || { cowork::warn "no core/agents dir"; return 0; }

  cowork::log "copilot: installing agents -> $target"
  mkdir -p "$target"
  local entry
  for entry in "$src"/*.md; do
    [[ -f "$entry" ]] || continue
    if ! cowork::targets_tool "$entry" "copilot"; then
      cowork::dim "   skipping $(basename "$entry") (tools: excludes copilot)"
      continue
    fi
    cowork::link "$entry" "$target/$(basename "$entry")"
  done
}

adapter_copilot::install_mcp() {
  local target_dir; target_dir="$(adapter_copilot::target)"
  local src="$COWORK_ROOT/core/mcp/servers.json"
  [[ -f "$src" ]] || { cowork::warn "no core/mcp/servers.json"; return 0; }

  local target_file="$target_dir/mcp.template.json"
  cowork::log "copilot: copying MCP template -> $target_file"
  cp "$src" "$target_file"
  cowork::dim "   merge interesting servers into your Copilot MCP config manually"
}

adapter_copilot::install() {
  local categories="${1:-all}"

  cowork::log "copilot: target = $(adapter_copilot::target)"
  if ! adapter_copilot::detect; then
    cowork::warn "copilot home not found at $(adapter_copilot::target); creating it"
    mkdir -p "$(adapter_copilot::target)"
  fi

  if [[ "$categories" == "all" || "$categories" == *skills*       ]]; then
    adapter_copilot::install_skills
  fi
  if [[ "$categories" == "all" || "$categories" == *rules*        ]]; then
    adapter_copilot::install_rules
  fi
  if [[ "$categories" == "all" || "$categories" == *agents*       ]]; then
    adapter_copilot::install_agents
  fi
  if [[ "$categories" == "all" || "$categories" == *mcp*          ]]; then
    adapter_copilot::install_mcp
  fi
}

adapter_copilot::uninstall() {
  local target; target="$(adapter_copilot::target)"
  cowork::log "copilot: removing artifacts pointing at $COWORK_ROOT"

  local dir entry
  for dir in "$target/skills" "$target/agents"; do
    [[ -d "$dir" ]] || continue
    for entry in "$dir"/*; do
      [[ -e "$entry" || -L "$entry" ]] || continue
      cowork::unlink_if_ours "$entry" "$COWORK_ROOT" || true
    done
  done

  # Rendered rules: remove only files we generated (marker comment present).
  if [[ -d "$target/instructions" ]]; then
    for entry in "$target/instructions"/*.instructions.md; do
      [[ -f "$entry" ]] || continue
      if grep -q 'Generated from .*adapters/copilot/adapter.sh' "$entry" 2>/dev/null; then
        rm "$entry"
        cowork::dim "   removed $entry"
      fi
    done
  fi

  if [[ -f "$target/mcp.template.json" ]]; then
    rm "$target/mcp.template.json"
    cowork::dim "   removed $target/mcp.template.json"
  fi
}

adapter_copilot::doctor() {
  local target; target="$(adapter_copilot::target)"
  cowork::log "copilot doctor: target = $target"
  if ! adapter_copilot::detect; then
    cowork::warn "   target directory does not exist"
    return 1
  fi

  local ok fail entry target_path

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/skills/*/; do
    [[ -d "$entry" ]] || continue
    target_path="$target/skills/$(basename "${entry%/}")"
    if [[ -L "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   skills:       $ok linked, $fail missing"

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/rules/*.md; do
    [[ -f "$entry" ]] || continue
    target_path="$target/instructions/$(basename "$entry" .md).instructions.md"
    if [[ -f "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   instructions: $ok rendered, $fail missing"

  ok=0; fail=0
  for entry in "$COWORK_ROOT"/core/agents/*.md; do
    [[ -f "$entry" ]] || continue
    target_path="$target/agents/$(basename "$entry")"
    if [[ -L "$target_path" ]]; then ok=$((ok + 1)); else fail=$((fail + 1)); fi
  done
  cowork::info "   agents:       $ok linked, $fail missing"

  [[ -f "$target/mcp.template.json" ]] && cowork::info "   mcp:          template present" || cowork::info "   mcp:          no template"
}
